name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "fastify-siwe-example-backend"
          heroku_email: "przemyslaw.rzad@trusttoken.com"
        env:
          PNPM_VERSION: 7.1.9
